$('#gconfig').click(function () {
    $('#inputconfig')[0].value = '#Generated by ControlCenter\n' +
        'server {' + '\n' +
        'listen 80;' + '\n' +
        'listen [::]:80;' + '\n' +
        'server_name ' + $('#inputName')[0].value + ';' + '\n' +
        'index index.html index.htm index.php default.html default.htm default.php;' + '\n' +
        'root  /web/vhost/' + $('#inputName')[0].value + ';' + '\n';
        if($('#return301')[0].checked){
            $('#inputconfig')[0].value +='return 301 https://' + $('#inputName')[0].value + '$request_uri;' + '\n'
        }
        if($('#gzip')[0].checked){
            $('#inputconfig')[0].value +='gzip on;' + '\n'
        }
        $('#inputconfig')[0].value +='location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$' + '\n' +
        '{' + '\n' +
        '    expires      30d;' + '\n' +
        '}' + '\n' +
        'location ~ .*\.(js|css)?$' + '\n' +
        '{' + '\n' +
        '    expires      12h;' + '\n' +
        '}' + '\n' +
        'location ~ /.well-known {' + '\n' +
        'allow all;' + '\n' +
        '}' + '\n' +
        'location ~ /\.{' + '\n' +
        '   deny all;' + '\n' +
        '}' + '\n' +
        'access_log off;' + '\n' +
        '}';
    if ($('#tls')[0].options.selectedIndex != 0) {
        $('#inputconfig')[0].value += '\nserver' + '\n' +
            '{' + '\n' +
            'listen 443 ssl http2;' + '\n' +
            'listen[::]: 443 ssl http2;' + '\n' +
            'server_name ' + $('#inputName')[0].value + ';' + '\n' +
            'index index.html index.htm index.php default.html default.htm default.php;' + '\n' +
            'root/web/vhost/' + $('#inputName')[0].value + ';' + '\n';
            if($('#gzip')[0].checked){
                $('#inputconfig')[0].value +='gzip on;' + '\n';
            }
            $('#inputconfig')[0].value +='ssl on;' + '\n' +
            'ssl_certificate /web/ssl/' + $('#tls')[0].options[$('#tls')[0].options.selectedIndex].text + '/'+$('#tls')[0].options[$('#tls')[0].options.selectedIndex].text+'.fc;' + '\n' +
            'ssl_certificate_key /web/ssl/' + $('#tls')[0].options[$('#tls')[0].options.selectedIndex].text + '/' + $('#tls')[0].options[$('#tls')[0].options.selectedIndex].text + '.key;' + '\n' +
            'ssl_session_timeout 5m;' + '\n' +
            'ssl_protocols TLSv1.2 TLSv1.3;' + '\n' +
            'ssl_prefer_server_ciphers on; ' + '\n' +
            'ssl_ciphers "TLS13-AES-256-GCM-SHA384:TS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-AES-128-CCM-8-SHA256:EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5";' + '\n' +
            'ssl_session_cache builtin:1000 shared:SSL:10m;' + '\n' +
            '# openssl dhparam-out /usr/local/nginx/conf/ssl/dhparam.pem 2048' + '\n' +
            '# ssl_dhparam /usr/local/nginx/conf/ssl/dhparam.pem;' + '\n' +
            '#HSTS' + '\n' +
            '#add_header Strict-Transport-Security "max-age=31536000; includeSubDomains;preload" always;' + '\n' +
            '#include rewrite/none.conf;' + '\n' +
            '#error_page   404/404.html;' + '\n' +
            'location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)${' + '\n' +
            '   expires      30d;' + '\n' +
            '}' + '\n' +
            'location ~ .*\.(js|css) ? ${' + '\n' +
            '   expires      12h;' + '\n' +
            '}' + '\n' +
            'location ~ /.well-known {' + '\n' +
            'allow all;' + '\n' +
            '}' + '\n' +
            'location ~ /\.{' + '\n' +
            '    deny all;' + '\n' +
            '}' + '\n' +
            'access_log off;' + '\n' +
            '}'
    }

})